[package]
name = "sol-dev-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
sha2 = { version = "0.10.8", features = ["std"] }

[package.metadata.cargo-machete]
ignored = ["proc-macro2"]

