[package]
name = "sol-dev-macros"

version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Solana development macros"
keywords.workspace = true
categories.workspace = true
